version: "3"
services:
  test:
    image: "exercise-2"
    volumes:
      - .:/app
    command: python3 -m pytest
  run:
    image: "exercise-2"
    build: ./
    volumes:
      - .:/app
    command: python3 main.py
